name: Publish

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "14.15.3"
          registry-url: https://registry.npmjs.org/
      - run: git config --global user.name maldan
      - run: git config --global user.email blackwanted@yandex.ru

      - run: npm install -g nexe
      - run: cd backend && npm ci && npm run build && cd bin && nexe ./index.js -t windows-x86-14.15.3 -o app.exe
      - run: cd frontend && npm ci && npm run build

      - run: mkdir bundle
      - run: cp ./backend/bin/app.exe ./bundle
      - run: cp -r ./frontend/build ./bundle
      - run: sudo apt install zip
      - run: cd ./bundle; zip -r application.zip *; mv application.zip ..

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: "latest"
          title: "Application Build"
          files: |
            application.zip
